module.exports = {
    'Abbess': {
        faction: "the sacred order",
        affinity: "force",
        hp: 14040,
        atk: 1564,
        def: 1079,
        spd: 96,
        crate: 15,
        cdmg: 63,
        res: 30,
        acc: 10
    },
    'Arbiter': {
        faction: "high elves",
        affinity: "void",
        hp: 21135,
        atk: 1068,
        def: 1101,
        spd: 110,
        crate: 15,
        cdmg: 50,
        res: 30,
        acc: 10
    },
    'Belanor': {
        faction: "high elves",
        affinity: "void",
        hp: 15195,
        atk: 1520,
        def: 1046,
        spd: 105,
        crate: 15,
        cdmg: 63,
        res: 30,
        acc: 10
    },
    'Bellower': {
        faction: "orgyn tribes",
        affinity: "void",
        hp: 16515,
        atk: 1013,
        def: 914,
        spd: 99,
        crate: 15,
        cdmg: 50,
        res: 30,
        acc: 15
    },
    'Ignatius': {
        faction: 'orgyn tribes',
        affinity: 'magic',
        hp: 18825,
        atk: 1057,
        def: 1266,
        spd: 93,
        crate: 15,
        cdmg: 50,
        res: 40,
        acc: 20
    },
    'Luria': {
        faction: "dark elves",
        affinity: "spirit",
        hp: 13050,
        atk: 1487,
        def: 947,
        spd: 104,
        crate: 15,
        cdmg: 50,
        res: 30,
        acc: 10
    },
    'Maulie': {
        faction: "dwarves",
        affinity: "spirit",
        hp: 18495,
        atk: 881,
        def: 1465,
        spd: 107,
        crate: 15,
        cdmg: 50,
        res: 80,
        acc: 10
    },
    'Rotos': {
        faction: 'undead hordes',
        affinity: 'magic',
        hp: 11895,
        atk: 1520,
        def: 1266,
        spd: 90,
        crate: 15,
        cdmg: 63,
        res: 40,
        acc: 0
    },
    'Septimus': {
        faction: 'banner lords',
        affinity: 'spirit',
        hp: 13710,
        atk: 1674,
        def: 991,
        spd: 102,
        crate: 15,
        cdmg: 63,
        res: 30,
        acc: 0
    }
};